apiVersion: apps/v1
kind: Deployment
metadata:
  name: jglkjslp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jglkjslp
  template:
    metadata:
      labels:
        app: jglkjslp
    spec:
      containers:
      - image: okteto.dev/jglkjslp:latest
        name: jglkjslp
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "ec114637-4d51-4244-9b55-20843677a918"
        - name: Vless_Path
          value: "/vlgrfri1555"
        - name: Vmess_UUID
          value: "ec114637-4d51-4244-9b55-20843677a918"
        - name: Vmess_Path
          value: "/vmjio15666"
        - name: Share_Path
          value: "/v2link"
